# Generated by Django 5.2.5 on 2025-09-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название заголовка статьи", max_length=100, verbose_name="Заголовок"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Укажите содержимое статьи", null=True, verbose_name="Содержимое"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="myblog/image",
                        verbose_name="Превью (изображение)",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True, help_text="Укажите дату создания", null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату последнего изменения",
                        null=True,
                        verbose_name="Дата последнего изменения",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["title", "created_at", "views"],
            },
        ),
    ]
