# Generated by Django 5.2.5 on 2025-11-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_blogpost_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["title", "created_at", "views_counter"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
