# Generated by Django 5.2.5 on 2025-11-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0003_alter_blogpost_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["title", "created_at", "views_counter"],
                "permissions": [("can_unpublish_blogpost", "Can unpublish blogpost")],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
