# Generated by Django 5.2.5 on 2025-09-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="catalog/image",
                verbose_name="Изображение",
            ),
        ),
    ]
