# Generated by Django 5.2.5 on 2025-09-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
            ),
        ),
    ]
